import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F7F3EE" },
  header: {
    height: 100,
    backgroundColor: "#4C2A13",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  headerTitle: { color: "#FFF", fontSize: 20, fontWeight: "bold" },
  content: { padding: 20, paddingBottom: 120 }, 
  patientLabel: {
    backgroundColor: "#EFE1C4",
    padding: 10,
    borderRadius: 15,
    marginBottom: 20,
    alignItems: "center",
  },
  patientLabelText: { color: "#4C2A13", fontWeight: "bold" },
  uploadBox: {
    height: 220,
    backgroundColor: "#D4C3A3",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginBottom: 25,
    borderStyle: "dashed",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  previewImage: { width: "100%", height: "100%" },
  uploadBoxTitle: { color: "#FFF", fontSize: 16, fontWeight: "bold", marginTop: 10 },
  formContainer: { marginBottom: 20 },
  inputLabel: { color: "#4C2A13", fontWeight: "bold", marginBottom: 8, marginLeft: 5 },
  input: {
    backgroundColor: "#FFF",
    borderRadius: 15,
    padding: 15,
    fontSize: 16,
    color: "#4C2A13",
    marginBottom: 15,
  },
  datePickerBtn: {
    backgroundColor: "#FFF",
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    justifyContent: "center",
  },
  mainBtn: {
    backgroundColor: "#4C2A13",
    padding: 18,
    borderRadius: 20,
    alignItems: "center",
    marginTop: 10,
    elevation: 5,
  },
  mainBtnText: { color: "#FFF", fontSize: 18, fontWeight: "bold" },
  clearFormBtn: { marginTop: 15, alignItems: "center" },
  clearFormText: { color: "#BC6C25", fontWeight: "bold", textDecorationLine: "underline" },
});