import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F3EE',
  },

  // Header Section
  topHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 10 : 20,
    height: 80,
    backgroundColor: "#4C2A13",
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 28,
    fontFamily: Platform.OS === 'serif' ? 'serif' : 'System',
    fontWeight: 'bold',
    color: '#fff',
  },

  scrollContent: {
    paddingBottom: 120,
    alignItems: 'center',
  },

  profileContainer: {
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 25,
  },
  imageWrapper: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#FFF',
    padding: 3,
    borderWidth: 1,
    borderColor: '#D4C3A3',
    shadowColor: '#4C2A13',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  profileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 72,
    backgroundColor: '#E8E4D9',
  },
  patientNameText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#4C2A13',
    marginTop: 20,
    fontFamily: Platform.OS === 'serif' ? 'serif' : 'System',
    textAlign: 'center',
    paddingHorizontal: 20,
  },

  engagementCard: {
    backgroundColor: '#4C2A13',
    width: width * 0.9,
    borderRadius: 40,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
    marginTop: 10,
  },
  cardLabel: {
    color: '#D4C3A3',
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: '600',
    marginBottom: 25,
    textTransform: 'uppercase',
  },
  outerRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  percentageText: {
    color: '#FFF',
    fontSize: 48,
    fontWeight: 'bold',
  },
  engagementStatus: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: '600',
    marginTop: 5,
  },
  updateText: {
    color: '#A89F91',
    fontSize: 13,
    marginTop: 8,
    fontStyle: 'italic',
  },

  lifeStoryCard: {
    backgroundColor: '#FFF',
    width: width * 0.9,
    borderRadius: 30,
    padding: 25,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#EFE1C4',
    shadowColor: '#4C2A13',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  lifeStoryTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#4C2A13',
    marginBottom: 10,
    fontFamily: Platform.OS === 'serif' ? 'serif' : 'System',
  },
  lifeStorySubtitle: {
    fontSize: 14,
    color: '#8A7B6A',
    lineHeight: 20,
    marginBottom: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F3EE',
    borderRadius: 20,
    paddingLeft: 15,
    borderWidth: 1,
    borderColor: '#D4C3A3',
  },
  keywordInput: {
    flex: 1,
    height: 60,
    fontSize: 16,
    color: '#4C2A13',
  },
  addButton: {
    backgroundColor: '#4C2A13',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  tagCloud: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 15,
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFE1C4',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 15,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: '#4C2A13',
    fontWeight: '600',
    fontSize: 14,
  },
  submitButton: {
    backgroundColor: '#606C38',
    borderRadius: 20,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 15,
  },
  submitButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },

  sideTabsContainer: {
    position: 'absolute',
    top: 80,
    width: width * 0.65,
    zIndex: 1000,
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 42, 19, 0.95)',
    paddingVertical: 18,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  rightTabItem: {
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
  },
  tabLabel: {
    color: '#FFF',
    fontSize: 15,
    marginLeft: 12,
    fontWeight: '600',
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmBox: {
    width: '85%',
    backgroundColor: '#FDFBFA',
    borderRadius: 25,
    padding: 30,
    alignItems: 'center',
  },
  confirmTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4C2A13',
    marginTop: 15,
    marginBottom: 10,
  },
  confirmSubtitle: {
    fontSize: 16,
    color: '#8A7B6A',
    textAlign: 'center',
    marginBottom: 25,
  },
  confirmButtons: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: '#EFE1C4',
    paddingVertical: 15,
    borderRadius: 12,
    marginRight: 8,
    alignItems: 'center',
  },
  cancelBtnText: { color: '#4C2A13', fontWeight: '700' },
  confirmBtn: {
    flex: 1,
    backgroundColor: '#d32f2f',
    paddingVertical: 15,
    borderRadius: 12,
    marginLeft: 8,
    alignItems: 'center',
  },
  confirmBtnText: { color: '#FFF', fontWeight: '700' },
});