import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F3EE', 
  },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 10 : 20,
    height: 100,
    backgroundColor: "#4C2A13",
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  silahLogo: {
      color: "#FFF", fontSize: 26, fontWeight: "bold", letterSpacing: 2 ,

  },

 
  content: {
    paddingBottom: 100, 
    paddingHorizontal: 20,
  },
  welcomeText: {
    fontSize: 32,
    lineHeight: 40,
    color: '#4C2A13',
    fontFamily: Platform.OS === 'serif' ? 'serif' : 'System',
  },
  highlightText: {
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: '#7A4A2E', 
  },

  actionButton: {
    backgroundColor: '#FFF',
    borderRadius: 30,
    shadowColor: '#4C2A13',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#EFE1C4',
  },
  iconCircle: {
    backgroundColor: '#F7F3EE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#4C2A13',
    letterSpacing: 0.5,
  },

  sideTabsContainer: {
    position: 'absolute',
    top: 80,
    right: 0,
    width: width * 0.65,
    backgroundColor: 'transparent',
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 42, 19, 0.95)', 
    paddingVertical: 18,
    paddingHorizontal: 20,
    marginBottom: 10,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 8,
  },
  tabLabel: {
    color: '#FFF',
    fontSize: 16,
    marginLeft: 12,
    fontWeight: '600',
  },

  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)', 
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmBox: {
    width: '85%',
    backgroundColor: '#FDFBFA',
    borderRadius: 25,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  confirmTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4C2A13',
    marginTop: 15,
    marginBottom: 10,
  },
  confirmSubtitle: {
    fontSize: 16,
    color: '#8A7B6A',
    textAlign: 'center',
    marginBottom: 25,
    lineHeight: 22,
  },
  confirmButtons: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: '#EFE1C4',
    paddingVertical: 15,
    borderRadius: 12,
    marginRight: 8,
    alignItems: 'center',
  },
  cancelBtnText: {
    color: '#4C2A13',
    fontWeight: '700',
    fontSize: 16,
  },
  confirmBtn: {
    flex: 1,
    backgroundColor: '#d32f2f', 
    paddingVertical: 15,
    borderRadius: 12,
    marginLeft: 8,
    alignItems: 'center',
  },
  confirmBtnText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 16,
  },
  lifeStoryCard: {
    backgroundColor: '#FFF',
    borderRadius: 25,
    padding: 20,
    marginBottom: 20,
    elevation: 4,
    shadowColor: '#4C2A13',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  lifeStoryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4C2A13',
    marginBottom: 8,
  },
  lifeStorySubtitle: {
    fontSize: 13,
    color: '#8A7B6A',
    lineHeight: 18,
    marginBottom: 15,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  keywordInput: {
    flex: 1,
    backgroundColor: '#F7F3EE',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    color: '#4C2A13',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#EFE1C4',
  },
  addButton: {
    backgroundColor: '#7A4A2E',
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  tagCloud: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFE1C4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: '#4C2A13',
    fontWeight: '600',
    fontSize: 13,
  },
  submitButton: {
    backgroundColor: '#606C38',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  submitButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  actionButton: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderWidth: 1,
    borderColor: '#EFE1C4',
    elevation: 2,
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F7F3EE',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  actionButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4C2A13',
  },
});